### ISSUE TITLE
Vue 3 Compatibility

### ISSUE THREAD

**Issue by rgehrsitz** [jledentu/vue-finder#183]
Any chance that Vue 3 compatibility will be added in the future?

Edit by the maintainer: there is a [3.0.1](https://github.com/jledentu/vue-finder/releases/tag/v3.0.1) pre-release supporting Vue 3. I invite you to test this version.

**Comment by jledentu** [comment]
@rgehrsitz Yes, I'm currently working on it. I've got a local branch where all the tooling (building, testing, linting) has been adapted. There is still some work to do to make drag & drop functional on my Vue 3 branch.

I don't know yet when I'll publish a first Vue 3 version, but it's in progress. 👍

**Comment by rgehrsitz** [comment]
Woohoo!

**Comment by smerchkz** [comment]
> 
@jledentu 
can you give access to this test branch, I would already use the component in vue3)))

**Comment by jledentu** [comment]
@smerchkz Hi, I pushed a `next` branch on the repository. But there is still no published prerelease version on npm.

Current status:
- [x] I think that the library itself is now ok on Vue3
- [x] Some tools have been upgraded (Storybook, Webpack replaced by Vite, Vuepress)
- [ ] Some samples in the docs are broken due to Vuepress config
- [ ] Unit tests have not been migrated
- [ ] A Storybook story is broken

**Comment by jledentu** [comment]
Hi,

A pre-release is available:

https://github.com/jledentu/vue-finder/releases/tag/v3.0.0

**Comment by tomcoonen** [comment]
Added PR to add Vite CSS import compatibility #188

**Comment by jledentu** [comment]
Hi,

The latest [v4.0.0](https://github.com/jledentu/vue-finder/releases/tag/v4.0.0) brings Vue 3 support in main release channel. The 2.x branch is now the maintenance branch of the Vue 2 version.
